# Generated by Django 4.1.3 on 2022-11-25 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('pre_requisites', models.TextField()),
                ('test_steps', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('case_status', models.CharField(choices=[('p', 'Passed'), ('f', 'Failed'), ('n', 'New'), ('i', 'In progress')], default='New', max_length=2)),
                ('automated', models.CharField(choices=[('a', 'Automated'), ('m', 'Manual')], max_length=2)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.suite')),
            ],
        ),
    ]
